#!/bin/sh

# Usage: Get a list of all currently visible words:
#     sh tmuxcomplete words '' -a
#
# Get all visible words beginning with `foo`:
#     sh tmuxcomplete words ^foo -a
#
# Get all visible words beginning with `foo`, ignoring case:
#     sh tmuxcomplete words ^foo -a -i
#
# Get all visible lines beginning with `foo`:
#     sh tmuxcomplete lines ^foo -a

if [ -z "$TMUX_PANE" ]; then
    echo "Not running inside tmux!" 1>&2
    exit 1
fi

MODE="$1" PATTERN="$2" LISTARGS="$3" CAPTUREARGS="$4" GREPARGS="$5"

capturepane() {
    if tmux capture-pane -p >/dev/null 2>&1; then
        # tmux capture-pane understands -p -> use it
        xargs -n1 tmux capture-pane $1 -p -t
    else
        # tmux capture-pane doesn't understand -p (like version 1.6)
        # -> capture to paste-buffer, echo it, then delete it
        xargs -n1 -I{} sh -c "tmux capture-pane $1 -t {} && tmux show-buffer && tmux delete-buffer"
    fi
}

splitwords() {
    # copy lines and split words
    sed -e 'p;s/[^a-zA-Z0-9_]/ /g' |
    # split on spaces
    tr -s '[:space:]' '\n' |
    # remove surrounding non-word characters
    grep -o "\\w.*\\w"
}

splitlines() {
    # remove surrounding whitespace
    grep -o "\\S.*\\S"
}

# list all panes
tmux list-panes $LISTARGS -F '#{pane_active}#{window_active}-#{session_id} #{pane_id}' |
# filter out current pane (use -F to match $ in session id)
grep -v -F "$(tmux display-message -p '11-#{session_id} ')" |
# take the pane id
cut -d' ' -f2 |
# capture panes
capturepane "$CAPTUREARGS" |
# split words or lines depending on mode
( [ "$MODE" = "lines" ] && splitlines || splitwords ) |
# filter out words not matching pattern
grep "$PATTERN" $GREPARGS |
# sort and remove duplicates
sort -u
